import { NextRequest, NextResponse } from 'next/server'
import { runNewsGenerationPipeline } from '@/lib/news-orchestrator'
import { getArticleStats } from '@/lib/news-publisher'

// Cron job configuration - runs every 6 hours
export const maxDuration = 300 // 5 minutes max execution time

/**
 * POST /api/news/generate
 * Manually trigger news generation (for testing or manual runs)
 */
export async function POST(request: NextRequest) {
  if (process.env.VERCEL_ENV !== 'production') {
    return NextResponse.json({ error: 'Unavailable in non-production environments' }, { status: 404 })
  }

  try {
    // Optional: Add authentication check here
    const authHeader = request.headers.get('authorization')
    const cronSecret = process.env.CRON_SECRET
    
    // Allow if CRON_SECRET matches or no secret is set (development)
    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const body = await request.json().catch(() => ({}))
    const count = Math.min(Number(body.count) || 2, 5) // Max 5 articles per run

    console.log(`[API] Starting news generation - ${count} articles requested`)
    
    const result = await runNewsGenerationPipeline(count)

    return NextResponse.json({
      success: result.success,
      message: result.success 
        ? `Successfully generated ${result.articlesGenerated} articles`
        : 'No articles were generated',
      data: result
    })

  } catch (error) {
    console.error('[API] News generation error:', error)
    return NextResponse.json(
      { 
        success: false,
        error: 'Failed to generate news articles',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

/**
 * GET /api/news/generate
 *
 * This is the endpoint Vercel Cron calls (cron jobs ALWAYS use GET).
 * - Default behavior: runs the news generation pipeline.
 * - With `?stats=true`: returns current auto-news stats instead.
 */
export async function GET(request: NextRequest) {
  if (process.env.VERCEL_ENV !== 'production') {
    return NextResponse.json({ error: 'Unavailable in non-production environments' }, { status: 404 })
  }

  const { searchParams } = new URL(request.url)

  // Stats-only mode (for dashboards / debugging)
  if (searchParams.get('stats') === 'true') {
    try {
      const stats = await getArticleStats()
      return NextResponse.json({
        success: true,
        stats: {
          totalAutoGenerated: stats.totalAuto,
          publishedToday: stats.todayCount,
          publishedThisWeek: stats.weekCount
        },
        nextScheduledRun: 'Every 6 hours via Vercel Cron'
      })
    } catch (error) {
      console.error('[API] Stats fetch error:', error)
      return NextResponse.json({ error: 'Failed to fetch stats' }, { status: 500 })
    }
  }

  // Otherwise, run the generation pipeline (this is what the cron triggers)
  try {
    // Vercel Cron automatically sends "Authorization: Bearer ${CRON_SECRET}"
    // when CRON_SECRET is set in the project env vars.
    const authHeader = request.headers.get('authorization')
    const cronSecret = process.env.CRON_SECRET

    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Number of articles to generate per scheduled run
    const count = Math.min(Number(searchParams.get('count')) || 2, 5)

    console.log(`[API] Cron triggered news generation - ${count} articles requested`)

    const result = await runNewsGenerationPipeline(count)

    return NextResponse.json({
      success: result.success,
      message: result.success
        ? `Successfully generated ${result.articlesGenerated} articles`
        : 'No articles were generated',
      data: result
    })
  } catch (error) {
    console.error('[API] Cron news generation error:', error)
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to generate news articles',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}
